services:  
  db:  
    image: mysql:8.4  
    restart: always  
    environment:  
      MYSQL_DATABASE: wordpress  
      MYSQL_USER: test  
      MYSQL_PASSWORD: test  
      MYSQL_ROOT_PASSWORD: test  # Root password for MySQL  
    volumes:  
      - db:/var/lib/mysql  

  wordpress:  
    image: wordpress  
    restart: always  
    ports:  
      - 8080:80  
    environment:  
      WORDPRESS_DB_HOST: db  
      WORDPRESS_DB_USER: test  
      WORDPRESS_DB_PASSWORD: test  
      WORDPRESS_DB_NAME: wordpress  # Ensure this matches the database name in the `db` service  
    volumes:  
      - ./wordpress:/var/www/html  
    depends_on:  
      - db  

  phpmyadmin:  
    image: phpmyadmin 
    restart: always  
    ports:  
      - 8081:80  
    environment:  
      PMA_HOST: db  
      MYSQL_ROOT_PASSWORD: test  # Match the root password from the `db` service  
    depends_on:  
      - db  

volumes:  
  wordpress:  
  db:  